### ISSUE TITLE
Is multiple ispc file support lost?

### ISSUE THREAD

**Issue by qatnonoil** [ispc/ispc#1233]
I wolud like to link multipile ispc files on Windows MSVC 2015.

```
// a.ispc
#include "b.isph"
export void test(){ func(); }
```

```
// b.isph
void func();
```

```
// b.ispc.
void func(){ print("B\n"); }
```

They're compiled with 

> ispc -O2 %(Filename).ispc -o %(Filename).obj -h %(Filename)_ispc.h --target=sse4,avx2 --wno-perf

..and main.cpp is like this.

```
#include "a_ispc.h"
void main() {ispc::test();}
```

In version 1.8.2, Problem did not occur.
In version 1.9.1, Linker outputs a lot of errors.

> 1>a_avx2.obj : error LNK2005: programCount は既に a_sse4.obj で定義されています。
>                                                ("programCount is already defined in a_sse4.obj.")
> 1>a_avx2.obj : error LNK2005: programIndex は既に a_sse4.obj で定義されています。
> 1>a_avx2.obj : error LNK2005: __math_lib は既に a_sse4.obj で定義されています。
> 1>a_avx2.obj : error LNK2005: __math_lib_ispc は既に a_sse4.obj で定義されています。
> 1>a_avx2.obj : error LNK2005: __math_lib_ispc_fast は既に a_sse4.obj で定義されています。
> 1>a_avx2.obj : error LNK2005: __math_lib_svml は既に a_sse4.obj で定義されています。
> 1>a_avx2.obj : error LNK2005: __math_lib_system は既に a_sse4.obj で定義されています。
> 1>a_avx2.obj : error LNK2005: __have_native_half は既に a_sse4.obj で定義されています。
> 1>a_avx2.obj : error LNK2005: __have_native_rand は既に a_sse4.obj で定義されています。
> ...

How do I fix it?

Thanks.

**Comment by jamesrburgess** [comment]
Hi,
 I upgrade to 1.9.1 because of the sprintf/iob problem in 1.8.1 and I'm having the same issue. Is there any progress on this?

Were these symbols marked COMDAT before and folded automatically or are they new and they are going to prohibit linking multiple .o's?

- James

Compiled in the same way as qatnonoil's example and also linked with VS2015 sp3
`PxrSurfaceFactorySampling.o : error LNK2005: programCount already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: programIndex already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __math_lib already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __math_lib_ispc already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __math_lib_ispc_fast already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __math_lib_svml already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __math_lib_system already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __have_native_half already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __have_native_rand already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __have_native_transcendentals already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __have_native_trigonometry already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __have_native_rsqrtd already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __have_native_rcpd already defined in PxrSurfaceSampling.o
PxrSurfaceFactorySampling.o : error LNK2005: __is_nvptx_target already defined in PxrSurfaceSampling.o
`

**Comment by jamesrburgess** [comment]
Some poking about reveals that unlike 1.8.1, 1.9.1 puts all these symbols in one section. 1.8.1 puts each library function in its own section. This is like cl.exe's /Gy option which I believe lets the linker choose one rather than throw "multiply defined" errors. I'm not sure that's the intended use of /Gy, just what it happens to do

**Comment by qatnonoil** [comment]
Great!
Thanks.
