### ISSUE TITLE
Constructors for short vector types

### ISSUE THREAD

**Issue by zigguratvertigo** [ispc/ispc#1279]
Hi!

Just like how constructors work with structs and new:
```
struct float3 { float x, y, z; };
float3* p = new float3(10, 20, 30);
```

Would be awesome if it worked without "new":
```
struct float3 { float x, y, z; };
float3 p = float3(10, 20, 30);
```

And it would be even more awesome to be able to do the same with short vector types:
```
typedef float<3> float3;
float3 p = float3(10, 20, 30);
```

-Colin

**Comment by dbabokin** [comment]
What about using the following syntax:
```
struct float3 { float x, y, z; };
float3 p = {10, 20, 30};
```

```
typedef float<3> float3;
float3 p = {10, 20, 30};
```

**Comment by zigguratvertigo** [comment]
Hey Dmitry,

I'm aware of the syntax you suggested. ;)

Originally I tried re-implementing the short vector float3 type like in your first example. Unfortunately there is so much underlying/additional functionality provided with the short vector types that one simply can't replicate (or declare/define) with a matching struct type. The first example that that comes to mind is swizzling (.xzy), but there a few others. If I was able to re-implement all the functionality that one can find with short vector types in struct, I would've taken that route since structs allow for the constructors.

In the meantime, I've been using the 2nd example you suggested. Ultimately I would like to replicate the HLSL syntax as much as possible.

float3 p = float3(10, 20, 30);
instead of
float3 p = {10, 20, 30};

If the previous was possible, then one of the key discrepancies allowing me to move HLSL to ISPC would be fixed. 

For now I've been emulating the functionality as such:

typedef float<3> float3;
float3 Float3(float x, float y, float z) { float3 r = { x, y, z }; return r; }
#define float3(x, y, z) Float3(x, y, z)

Would be ace if the constructor for short vector types took the same number of arguments as the short float type element count! :D

**Comment by dbabokin** [comment]
I was looking at this request and wondering if float3(1,2,3) syntax is the right approach. HLSL/GLSL use it, while OpenCL uses (float3)(1,2,3). I've tried to dig to the reasons behind this and all that I was able to find is that it's probably more familiar for C programmers, as it looks like a cast. But it is quite strange cast in my opinion. So, we'll go forward and add float3(1,2,3) constructor-like syntax.

**Comment by dbabokin** [comment]
This issue appeared to be way more challenging than I expected. This syntax is not available in C, it's a C++ feature. I.e. in C "int(1)" is not a valid int constructor. The reason is that it greatly complicates parser and makes it impossible to parse the language with simple LALR(1) parser (for example, with bison grammar, which is used in ISPC). The real conflict can be demonstrated by the following statements:
```
int(*foo)(); // function pointer declarator
int(1); // int initialization with constant 1
```
I've checked how C++ deals with this and looked at clang implementation. It actually tries parsing declarator first and when/if it fails, it rolls back and parses this as type constructor expression (clang::Parser::ParseCXXTypeConstructExpression() function in clang).

So I'm afraid with current bison parser we cannot fix this.
