### ISSUE TITLE
I'm trying to understand what the difference semantically is between these two loops

### ISSUE THREAD

**Issue by ronniec95** [ispc/ispc#1286]
```
export void ema(uniform float vin[], uniform float vout[], const uniform int count, const uniform float period) {
    uniform float alpha = 1.0f / period;
	float prev = vin[0];
    for (uniform int i = 1 ; i < count; i++) {
        float       v    = vin[i];
        prev  = alpha * v + (1.0f - alpha) * prev;
    }
}
```

and

```
export void ema(uniform float vin[], uniform float vout[], const uniform int count, const uniform float period) {
    uniform float alpha = 1.0f / period;
	float prev = vin[0];
    foreach (i = 1 .. count) {
        float       v    = vin[i];
        prev  = alpha * v + (1.0f - alpha) * prev;
    }
}
```

I would have thought exactly the same, but the second one gives me a **Performance Warning: Gather required to load value.**

What is the best way to write something like this loop?

**Comment by ifilippov** [comment]
This happens due to the following:

Within each foreach loop iteration "i" counter is varying. At the first loop iteration it is 0,1,2,3... So you load vin[i] from a varying index. You have to use gather to load an array values with varying index, because you load array values from different places.

At your first example you have uniform counter "i", so you will load only one array value at each loop iteration, which will be than cast to varying "v" by simply cloning to varying size.

**Comment by jbrodman** [comment]
The performance warning is a bug that should've been fixed with the latest
versions - which version are you running?
