### ISSUE TITLE
Compiling code from github

### ISSUE THREAD

**Issue by kingofthebongo2008** [ispc/ispc#1341]
Hello,

I am trying to build with LLVM from here:

https://github.com/llvm-mirror/llvm

To compile i had to change this:

%alignment = load PTR_OP_ARGS(`i32')  @memory_alignment

into this.

%alignment = load i32, PTR_OP_ARGS(`i32')  @memory_alignment

However i get this error also, where i have to look to fix it?

1>    C:/llvm/bin\llvm-as.exe: <stdin>(1803,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0

1>    C:/llvm/bin\llvm-as.exe: <stdin>(1806,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0
1>     ^
1>    Building gen-bitcode-generic-8-32bit.cpp and gen-bitcode-generic-8-64bit.cpp
1>    C:/llvm/bin\llvm-as.exe: <stdin>(1803,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0
1>     ^
1>    C:/llvm/bin\llvm-as.exe: <stdin>(1806,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0
1>     ^
1>    Building gen-bitcode-generic-16-32bit.cpp and gen-bitcode-generic-16-64bit.cpp
1>    C:/llvm/bin\llvm-as.exe: <stdin>(1803,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0
1>     ^
1>    C:/llvm/bin\llvm-as.exe: <stdin>(1806,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0
1>     ^
1>    Building gen-bitcode-generic-32-32bit.cpp and gen-bitcode-generic-32-64bit.cpp
1>    C:/llvm/bin\llvm-as.exe: <stdin>(1803,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0
1>     ^
1>    C:/llvm/bin\llvm-as.exe: <stdin>(1806,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0
1>     ^
1>    Building gen-bitcode-generic-64-32bit.cpp and gen-bitcode-generic-64-64bit.cpp
1>    C:/llvm/bin\llvm-as.exe: <stdin>(1803,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0
1>     ^
1>    C:/llvm/bin\llvm-as.exe: <stdin>(1806,2): error G94098AC4: expected comma after getelementptr's type
1>     %ret64, i32 0

**Comment by dbabokin** [comment]
You need to define LLVM_VERSION environment variable to a proper value, LLVM_8_0 if you are building trunk.

But the recommended way to build LLVM (of any version) is to use "alloy.py" script: "alloy.py -b --version=trunk" for example. Though I would recommend 6.0 instead of trunk for the moment. You need to defined LLVM_HOME to the path where you want to build LLVM. If you still prefer to build it manually, make sure to set "-DLLVM_ENABLE_DUMP=ON" to cmake. Otherwise dump() functions in LLVm will not be built, but they are required for ISPC.

We definitely need to update the documentation how to build ISPC, especially on Windows.

**Comment by kingofthebongo2008** [comment]
I am using code from github, because llvm-dis is missing from the official builds by the way.

**Comment by dbabokin** [comment]
It's not about building LLVM from source vs using pre-built binaries. It's about *how* you build LLVM from sources. Right way to build it is either define "-DLLVM_ENABLE_DUMP=ON" in CMake or use alloy.py, which would do all the work. After you done with building LLVM, you need to define env variable LLVM_VERSION to LLVM_8_0 (or whatever version you've built). The errors you are pasted in initial message are due to incorrect value of LLVM_VERSION (or not defining it at all).
