### ISSUE TITLE
Crash on outputting debug info with SOA

### ISSUE THREAD

**Issue by cwfitzgerald** [ispc/ispc#1375]
Found the problem when messing around on godbolt: https://godbolt.org/z/pt6qyn. Seems to be specifically related to the debug info that godbolt mandates. The problem only happens when optimization and debug info are on, otherwise it compiles cleanly.

**Comment by DeepakRajendrakumaran** [comment]
Hi,

Have you been able to reproduce this in an environment outside of godbolt(running from commandline in local machine for instance)? If yes, what are the command line switches you are passing in?

**'The problem only happens when optimization and debug info are on, otherwise it compiles cleanly.'**
Were you able to compile on godbolt by changing something? If yes, how? Or did you mean to say you were able to compile cleanly locally?

My apologies for the questions. I am having trouble reproducing it outside of godbolt so that'll be useful info.

-Deepak

**Comment by DeepakRajendrakumaran** [comment]
Never mind. Got it! :)

**Comment by DeepakRajendrakumaran** [comment]
This is an llvm issue. It's fixed by llvm 6.0. I'll see if i can add a patch to 5.0 in ispc

**Comment by cwfitzgerald** [comment]
Awesome, thanks!

**Comment by dbabokin** [comment]
Fixed.
