### ISSUE TITLE
Two Naive questions..

### ISSUE THREAD

**Issue by oscarbg** [ispc/ispc#1406]
Hi,
just seeing ISPC 1.10 released, I have two questions:
1) why using old LLVM version:"patched LLVM 5.0.2", bugs present in current LLVM 7.0.1 or soon to release LLVM 8.0?
2) Windows prebuilt binary (at  "https://ispc.github.io/downloads.html") is 32bit vs 64 bit binaries for Linux and Mac..
any reason to not ship 64 bit prebuilt Win binary?
thanks..

**Comment by dbabokin** [comment]
We use 5.0 because it's more stable for us. There are known bugs with 6.0 and 7.0. To make it clear - most of these bugs are not LLVM bugs, are more a problem of contract between ISPC and LLVM or the way we generate LLVM IR. We'll fix 6.0/7.0/8.0 bugs, but for now we've decided that it makes more sense to use 5.0.
The list of known fails is here: https://github.com/ispc/ispc/blob/master/fail_db.txt

For the choice between 32/64 bit - it's platform dependant. 32 bit doesn't exist on macOS in the modern world. Most of the Linux also lives on 64 bits. But for Windows still there's noticeable portion of users living on 32 bit, so it make sense to release 32 bit binary.

Note, that on all platforms you can generate both 32 and 64 bit binaries, regardless of the bitness of compiler itself. So I'm not sure that there's any value in separate 64 bit package. Please let know if I'm missing something.

**Comment by kingofthebongo2008** [comment]
If we can get 64 bit windows build will be great.

**Comment by dbabokin** [comment]
What are the limitation / inconveniences with 32 bit version in 64 bit environment, that you are trying to fix with 64 bit version?

**Comment by oscarbg** [comment]
thanks for answering.. make sense..
