### ISSUE TITLE
ispc-1.10.0 failure to build with gcc

### ISSUE THREAD

**Issue by luyatshimbalanga** [ispc/ispc#1413]
Hello team,
I tried to build ispc with gcc. Unfortunately, it failed at the following line:
```
BUILDSTDERR: /usr/bin/ld: kernels_ispc_sse2.o: relocation R_X86_64_32
against symbol
`RenderTile___uniuniREFs_5B_unInputHeader_5D_REFs_5B_unInputDataArrays_5D_uniun_3C_unT_3E_un_3C_unT_3E_un_3C_unT_3E_sse2'
can not be used when making a PIE object; recompile with -fPIC
BUILDSTDERR: /usr/bin/ld: kernels_ispc_sse4.o: relocation R_X86_64_32S
against `.rodata.cst16' can not be used when making a PIE object;
recompile with -fPIC
BUILDSTDERR: /usr/bin/ld: kernels_ispc_avx.o: relocation R_X86_64_32
against symbol
`RenderTile___uniuniREFs_5B_unInputHeader_5D_REFs_5B_unInputDataArrays_5D_uniun_3C_unT_3E_un_3C_unT_3E_un_3C_unT_3E_avx'
can not be used when making a PIE object; recompile with -fPIC
BUILDSTDERR: /usr/bin/ld: kernels_ispc_avx2.o: relocation R_X86_64_32S
against `.rodata.cst32' can not be used when making a PIE object;
recompile with -fPIC
BUILDSTDERR: /usr/bin/ld: kernels_ispc_avx512knl.o: relocation
R_X86_64_32 against symbol
`RenderTile___uniuniREFs_5B_unInputHeader_5D_REFs_5B_unInputDataArrays_5D_uniun_3C_unT_3E_un_3C_unT_3E_un_3C_unT_3E_avx512knl'
can not be used when making a PIE object; recompile with -fPIC
BUILDSTDERR: /usr/bin/ld: kernels_ispc_avx512skx.o: relocation
R_X86_64_32 against symbol
`RenderTile___uniuniREFs_5B_unInputHeader_5D_REFs_5B_unInputDataArrays_5D_uniun_3C_unT_3E_un_3C_unT_3E_un_3C_unT_3E_avx512skx'
can not be used when making a PIE object; recompile with -fPIC
BUILDSTDERR: /usr/bin/ld: final link failed: nonrepresentable section on
output
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[2]: ***
[examples/deferred/CMakeFiles/deferred_shading.dir/build.make:204:
bin/deferred_shading] Error 1
BUILDSTDERR: make[1]: *** [CMakeFiles/Makefile2:370:
examples/deferred/CMakeFiles/deferred_shading.dir/all] Error 2
BUILDSTDERR: make: *** [Makefile:133: all] Error 2
```
Here is the location of the spec file and the patches: https://src.fedoraproject.org/rpms/ispc/tree/master
You can view the discussion on Fedora Development mailing list: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/2XGYYERSZOADNA3IJMLPZPSOAP32SU4W/

**Comment by dbabokin** [comment]
I'm not familiar with build environment used for package build for Fedora, but it looks like that stock llvm is used (i.e. llvm-devel, clang-devel packages). ISPC requires manual llvm build (with set of patches and specific switches).

Also, llvm and ispc must be build with the same compiler (we typically use clang for both, but gcc should work as well, the point is that compiler must be the same) - this is due to an ABI bug in gcc, which causes link problems.

**Comment by luyatshimbalanga** [comment]
I don't use Docker so I don't know how it works.Here is the log from the built showing that gcc is the compiler:
https://kojipkgs.fedoraproject.org//work/tasks/4096/32324096/build.log

**Comment by dbabokin** [comment]
Ok, from what I see, stock version of LLVM is used, not a manually built version (via alloy.py script). That's bad way to build ISPC - it will yield broken ISPC build stability- and performance-wise.

Nevertheless, the bug you see is something different and it worth investigating. We'll try to reproduce it.

So, the receipt to build ISPC package is basically CMake+make command, right? Is it possible to do alloy.py+CMake+make? Would it fit package build process used by Fedora? If so, we'll provide instructions / wrapper script to do so.

**Comment by fweimer** [comment]
Fedora builders do not have Internet access, so they cannot download additional source code.
You really need to get your fixes into LLVM upstream. Fedora will not build LLVM anew for every LLVM-based project.
Anyway, the issue here is that Fedora defaults to PIE builds, but ispc produces non-PIE (non-PIC) object files by default. We tried to add the `--pic` option to the build command for the examples:

```
The examples are linked as PIE, so position-independent code is needed.
ispc only supports --pic, so use that.

diff --git a/examples/cmake/AddISPCExample.cmake b/examples/cmake/AddISPCExample.cmake
index dbd80e7643b9f803..a88d2e5279fad32a 100644
--- a/examples/cmake/AddISPCExample.cmake
+++ b/examples/cmake/AddISPCExample.cmake
@@ -93,7 +93,7 @@ function(add_ispc_example)
     endif()
     # ISPC command
     add_custom_command(OUTPUT ${ISPC_BUILD_OUTPUT}
-        COMMAND ${ISPC_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/${ISPC_SRC_NAME}.ispc ${example_ISPC_FLAGS} --target=${ISPC_TARGETS} --arch=${ISPC_ARCH}
+        COMMAND ${ISPC_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/${ISPC_SRC_NAME}.ispc ${example_ISPC_FLAGS} --pic --target=${ISPC_TARGETS} --arch=${ISPC_ARCH}
                                     -h ${ISPC_HEADER_NAME} -o ${ISPC_OBJ_NAME}
         VERBATIM
         DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/${ISPC_SRC_NAME}.ispc")
```

This resulted in an abort during the build:

```
cd /builddir/build/BUILD/ispc-1.10.0/examples/perfbench && ../../bin/ispc /builddir/build/BUILD/ispc-1.10.0/examples/perfbench/perfbench.ispc --pic --target=sse2-i32x4,sse4-i32x4,avx1-i32x8,avx2-i32x8,avx512knl-i32x16,avx512skx-i32x16 --arch=x86-64 -h /builddir/build/BUILD/ispc-1.10.0/examples/perfbench/perfbench_ispc.h -o /builddir/build/BUILD/ispc-1.10.0/examples/perfbench/perfbench_ispc.o
make[2]: Leaving directory '/builddir/build/BUILD/ispc-1.10.0'
/builddir/build/BUILD/ispc-1.10.0/src/main.cpp(353): FATAL ERROR: Unhandled signal sent to process; terminating.
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
make[2]: *** [examples/perfbench/CMakeFiles/perfbench.dir/build.make:65: examples/perfbench/perfbench_ispc.h] Aborted (core dumped)
```

**Comment by dbabokin** [comment]
LLVM for ISPC should be considered as sub-module of ISPC project. LLVM is not stable from ISPC prospective, i.e. it has multiple stability and performance regressions for *ISPC usage case*. I.e. they are not affecting clang stability and performance in most of the cases. We investigate these regressions and file issues. When they are fixed, we back-port fixes to older versions. As a result we have a recommended LLVM version to use (currently 5.0), which needs to be properly patched.

Would introducing LLVM dependancy as git sub-module help to build it as part of ISPC build in your environment?

For the specific problem with --pic, we are trying to reproduce it. I've heard that there were similar issues, which were caused by different compiler used to build LLVM and ISPC.

If you can give a Dockerfile, which reproduces the problem in the environment that you use, that would help a lot.

**Comment by luyatshimbalanga** [comment]
Unfortunately, Fedora builder does not use git sub-module.
Would you mind providing patches against stock LLVM?

**Comment by dbabokin** [comment]
All patches are in the folder llvm_patches. You need all the patches, which have LLVM version that you need in their name. I.e. if you are building LLVM 5.0, you need all patches matching *5_0* wildcard.

**Comment by luyatshimbalanga** [comment]
> If you can give a Dockerfile, which reproduces the problem in the environment that you use, that would help a lot.

Here is the dockerfile [ispc-fedora-dockerfile.txt](https://github.com/ispc/ispc/files/2897758/ispc-fedora-dockerfile.txt) to reproduce the issue.

**Comment by aneshlya** [comment]
I tried to build a docker with dockerfile provided but it breaks on rpmbuild step:
`-- Build files have been written to: /root/rpmbuild/BUILD/ispc-1.10.0
/usr/bin/make -O -j12 gcc 'OPT=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC' 'LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fPIC'`
`make: *** No rule to make target 'gcc'.  Stop.`
`Bad exit status from /var/tmp/rpm-tmp.cseoAL (%build)
The command '/bin/sh -c rpmbuild -D"_sourcedir ${PWD}" -D"_srcrpmdir ${PWD}" -ba ispc.spec' returned a non-zero code: 1`

But manual ispc build according to the spec file works fine:
`tar -xvf ispc-1.10.0.tar.gz` 
`cd ispc-1.10.0`
`sed -i 's|set(CMAKE_CXX_COMPILER "clang++")|set(CMAKE_CXX_COMPILER "g++")|g' CMakeLists.txt`
`sed -i 's|set(CMAKE_CXX_COMPILER "clang")|set(CMAKE_CXX_COMPILER "gcc")|g' CMakeLists.txt`
`cd ..`
`patch < 0002-Remove-uses-of-LLVM-dump-functions-and-verbose-makefile.patch `
`cd ../ispc-1.10.0`
`mkdir build && cd build`
`cmake -DISPC_INCLUDE_TESTS=OFF ../`
`make -j8`

Hovewer patching ISPC in order to make it work with stock LLVM is completely opposite to what we're asking for. It will bring unexpected stability and performance issues. 
There is only one way to build ISPC correctly - using patched version of stock LLVM. Also we recommend to use LLVM 5.0, not 7.0.

Is it possible to add one more "source" macro with path to llvm to the spec file and build it before ispc using alloy.py script?

**Comment by luyatshimbalanga** [comment]
> I tried to build a docker with dockerfile provided but it breaks on rpmbuild step:
> `-- Build files have been written to: /root/rpmbuild/BUILD/ispc-1.10.0 /usr/bin/make -O -j12 gcc 'OPT=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC' 'LDFLAGS=-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fPIC'`
> `make: *** No rule to make target 'gcc'. Stop.`

If you remove the 'gcc' target on the spec file, then it should be able to build until the PIE issue.

> But manual ispc build according to the spec file works fine:
> `tar -xvf ispc-1.10.0.tar.gz`
> `cd ispc-1.10.0`
> `sed -i 's|set(CMAKE_CXX_COMPILER "clang++")|set(CMAKE_CXX_COMPILER "g++")|g' CMakeLists.txt`
> `sed -i 's|set(CMAKE_CXX_COMPILER "clang")|set(CMAKE_CXX_COMPILER "gcc")|g' CMakeLists.txt`
> `cd ..`
> `patch < 0002-Remove-uses-of-LLVM-dump-functions-and-verbose-makefile.patch `
> `cd ../ispc-1.10.0`
> `mkdir build && cd build`
> `cmake -DISPC_INCLUDE_TESTS=OFF ../`
> `make -j8`
> 
> However patching ISPC in order to make it work with stock LLVM is completely opposite to what we're asking for. It will bring unexpected stability and performance issues.
> There is only one way to build ISPC correctly - using patched version of stock LLVM. Also we recommend to use LLVM 5.0, not 7.0.

Unfortunately, Fedora Project recently intend to retire LLVM 5.0 to focus to 7.0+ version instead.

> Is it possible to add one more "source" macro with path to llvm to the spec file and build it before ispc using alloy.py script?
See [this comment](https://github.com/ispc/ispc/issues/1413#issuecomment-458877295). Fedora builder does not have Internet access. Perhaps contacting the Fedora version of LLVM maintainer will be better to get a better approach using your patches. I filed a [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1680197) for that purpose.

**Comment by luyatshimbalanga** [comment]
I managed to advance the built further despite the failure by adding _	-DCMAKE_EXE_LINKER_FLAGS="%{optflags} -fPIE" \_ on cmake option. Now the failure occurs with this line
```
make[2]: *** Deleting file 'examples/perfbench/perfbench_ispc.h'
/builddir/build/BUILD/ispc-1.10.0/src/main.cpp(353): FATAL ERROR: Unhandled signal sent to process; terminating.
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
make[2]: *** [examples/perfbench/CMakeFiles/perfbench.dir/build.make:65: examples/perfbench/perfbench_ispc.h] Aborted (core dumped)
```

**Comment by luyatshimbalanga** [comment]
It turned out the failure occurs with the default ISPC_INCLUDE_EXAMPLES=ON when built with gcc. Turning off these examples resolves the issue.

**Comment by luyatshimbalanga** [comment]
Closing this report as resolved
