### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by drink18** [ispc/ispc#1468]
Hello, 
    I'm trying to use ISPC to optimize a mobile game target to arm64 support. To my surprise  the aarch64 support does not seem to exist. Is there any plan to support it or I missed something?

Cheer
Wei

**Comment by dbabokin** [comment]
Yes, we plan to add it in the next release.

**Comment by drink18** [comment]
@dbabokin That's great new! Thank you for the reply. Is there any ETA for this?

**Comment by dbabokin** [comment]
It depends on your expectations on the quality of the support.

We already started rolling out first patches. Right now we have quite a few fails just because of not implemented intrinsics. We'll be fixing them and I hope to get more or less stable version in about a month probably. But it's reasonable to expect that this target will be more buggy than others - just because it's new and quite different from x86 targets in some aspects.

**Comment by drink18** [comment]
Thanks for the reply. It's actually great new because I was thinking about DIYing it yesterda :)
It is understandalbe that the first few iteration will be buggy, but once I can get my hands on it I can probably fix/hack/ it to fit my needs. 
Looking forward  to it

**Comment by dbabokin** [comment]
Patches and feedback are always welcome :)

**Comment by myfreeweb** [comment]
The backend in git master works fine on my machine (4xCortex-A72@2GHz, FreeBSD -CURRENT, `clang++80 -O3 -mcpu=cortex-a72`) :)

```
@time of ISPC run:                      [2690.366] million cycles
@time of ISPC run:                      [2706.283] million cycles
@time of ISPC run:                      [2698.887] million cycles
[aobench ispc]:                 [2690.366] million cycles (640 x 480 image)
Wrote image file ao-ispc.ppm
@time of ISPC + TASKS run:                      [707.699] million cycles
@time of ISPC + TASKS run:                      [718.846] million cycles
@time of ISPC + TASKS run:                      [710.273] million cycles
[aobench ispc + tasks]:         [707.699] million cycles (640 x 480 image)
Wrote image file ao-ispc-tasks.ppm
@time of serial run:                            [6397.158] million cycles
@time of serial run:                            [6392.638] million cycles
@time of serial run:                            [6385.406] million cycles
[aobench serial]:               [6385.406] million cycles (640 x 480 image)
                                (2.37x speedup from ISPC, 9.02x speedup from ISPC + tasks)
Wrote image file ao-serial.ppm
```

Would be nice to see a numbered release soon so we could package it in FreeBSD Ports.

**Comment by dbabokin** [comment]
@myfreeweb Are you interested specifically in ARM support on FreeBSD? Is it vanilla FreeBSD or FreeBSD based port (like the OS on PS4)? Are you interested in host compilation or cross compilation?

**Comment by dbabokin** [comment]
@myfreeweb Also, do you expect us to release FreeBSD based binaries or you ok building the compiler yourself? I assume you care about 64 bit support only (aarch64), right?

Could you please show what triple clang is using on your system?
`clang -c test.c -emit-llvm -o - | llvm-dis | head`

**Comment by myfreeweb** [comment]
We already have it [packaged](https://www.freshports.org/devel/ispc) in Ports, all I've had to do is to update from 1.11.0 to `1.11.0-60-g150f1b1`, add `aarch64` to the `ONLY_FOR_ARCHS` list, and remove [the `alloca` patch](https://github.com/freebsd/freebsd-ports/blob/master/devel/ispc/files/patch-src_util.cpp) since the `alloca` include has been ifdef'd to Linux.

I'm not asking for any support, no binaries or anything like that (though not having local patches in Ports would be nice — seems like that would mostly mean [avoiding LLVM dump()](https://github.com/freebsd/freebsd-ports/blob/b8913acfe1dd2a69b163c6b503185ede87b779e9/devel/ispc/files/patch-src_opt.cpp)) but I'd like to know when the next release (that would include the aarch64 backend) is planned.

> what triple clang is using

`aarch64-unknown-freebsd13.0` (btw, `clang -v` just says that, no need for that disassembly incantation)

**Comment by dbabokin** [comment]
That's very timely information. I'm working on cross platform support and I was not aware that we have customers interested in ARM in FreeBSD.

The next release is coming shortly. FreeBSD builds were always strange beast for us, hope we will not mess it up.

**Comment by myfreeweb** [comment]
oh, one thing I forgot: I've had to disconnect the AVX backends because of an error:

```
FAILED: builtins-target-avx2-i32x4-32bit.cpp
cd /usr/ports/devel/ispc/work/ispc-1.11.0-60-g150f1b1 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=32 builtins/target-avx2-i32x4.ll | "/usr/local/bin/python2.7" bitcode2cpp.py builtins/target-avx2-i32x4.ll 32 --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x4-32bit.cpp
/usr/local/llvm80/bin/llvm-as: <stdin>:10028:119: error: expected type
  %v_1 = call <4 x i32> @llvm.x86.avx2.gather.d.d(<4 x i32> undef, i8 * %ptr, <4 x i32> %offsets, <4 x i32> %vecmask, v1 1)
                                                                                                                      ^
 ```

**Comment by dbabokin** [comment]
Does you llvm have x86 target built?

As for the patches, I would suggest contribute FreeBSD target to ISPC, at least the bits that do platform recognition. This will make the live easier. Also, building LLVM as part of ISPC build is the right way to go. FreeBSD folks were totally agains it, though.

**Comment by myfreeweb** [comment]
Of course, it has all the standard targets. SSE modules build fine. It's a syntax error ten thousand lines deep into AVX.

> bits that do platform recognition

That doesn't seem to be required. The only platform specific thing the patches add is `ISPC_USE_TBB_TASK_GROUP` because the pthread backend failed for someone in the past (I haven't retested that.)

> building LLVM as part of ISPC build is the right way to go. FreeBSD folks were totally agains it, though

Yeah, we don't like spending hours of build time and extra disk space on rebuilding a very slightly different version of a monster sized library :)

OS package distributions are all about sharing as much as possible and reducing waste.

**Comment by myfreeweb** [comment]
update: so the AVX thing is a difference with GNU and BSD `m4`, has nothing to do with aarch64 of course, just with the update from the last release to git master.

>  GNU m4 allows the number following the `$' to consist of one or more digits, allowing macros to have any number of arguments. This is not so in UNIX implementations of m4, which only recognize one digit.

— [docs](http://web.mit.edu/gnu/doc/html/m4_4.html)

and you have too much args there (`$11`) :) Setting `-DM4_EXECUTABLE` to GNU m4 fixes the problem.

**Comment by aneshlya** [comment]
Looks like this issue was resolved. Further aarch64 support will be covered in https://github.com/ispc/ispc/issues/3110
