### ISSUE TITLE
 warning LNK4003: invalid library format; library ignored

### ISSUE THREAD

**Issue by xoraxrax** [ispc/ispc#1506]
when i link object file with msvc2017

- 1.ispc
```CPP
 int32 get_strlen(int8* ptr) {
    int i = 0;
    while(*ptr != 0){
        i++;
    }
    return i;
}
```
> ispc 1.ispc --arch=x86 -o 1.obj

- test.cpp
```.CPP
extern "C" int _i_get_strlen___vy_3C_unt_3E_(const char* ptr);

int main(int argc , char *argv[] , char *envp[]) {
	auto len = _i_get_strlen___vy_3C_unt_3E_("123");
}

```

![image](https://user-images.githubusercontent.com/27957496/59401130-4dd28d80-8dcc-11e9-9a25-0bfd1a5ca0b9.png)

**Comment by pbrubaker** [comment]
ISPC will create a header file for you with the command line option `-h` which you then include in any C/C++ file you want to call the ISPC function from.

> The -h flag can also be used to direct ispc to generate a C/C++ header file that includes C/C++ declarations of the C-callable ispc functions and the types passed to it.

https://ispc.github.io/ispc.html#using-the-ispc-compiler

**Comment by stonedreamforest** [comment]
thanks, but i wanna known why there is different result:
[view 1](https://godbolt.org/z/0q74KZ
)
![image](https://user-images.githubusercontent.com/16742566/59410764-41f6c380-8dec-11e9-914f-0739e036fd41.png)

[view 2](https://godbolt.org/z/70XluE)
![image](https://user-images.githubusercontent.com/16742566/59410817-65217300-8dec-11e9-9454-da139a2d1e54.png)

----
i like **view 1** , Because it will be faster than view 2
