### ISSUE TITLE
--target=avx2-i32x16,avx512skx-i32x16 crashes ispc 1.12.0

### ISSUE THREAD

**Issue by mikemccarty-vertex** [ispc/ispc#1576]
Example:  https://ispc.godbolt.org/z/OumXQ5

Specifying only `--target=avx512skx-i32x16` or `--target=avx2-i32x16` works as expected.

**Comment by dbabokin** [comment]
The source is irrelevant, it crashes when processing options. @DeepakRajendrakumaran please have a look.

**Comment by DeepakRajendrakumaran** [comment]
The reason for the crash is during the removal of avx11, AVX11 was removed from ISA enum. This creates non continuous enums since we numbered the enums. We trying to iterate through all elements of the enum and convert it to string, ISAToTargetString() gets called with '3' which is not not supported.

**Comment by dbabokin** [comment]
Fixed.
Thanks for reporting this!
