### ISSUE TITLE
Maximum number of command-line arguments

### ISSUE THREAD

**Issue by Unit2Ed** [ispc/ispc#1636]
Unreal Engine has recently added straight-forward support for using ISPC in its build system - you simply drop an ispc file into your source, and it'll build & link it along with the rest of the code.

Unfortunately, Unreal projects tend to have a ton of include directories and produces very long command-lines. In attempting to use ispc, I've hit a wall because there's a 512 argument restriction - currently I'm seeing 670!

https://github.com/ispc/ispc/blob/a0c822ac5261d936f865730903655c16199a1f1d/src/main.cpp#L68

Is the 512 limit meaningful? It looks like it's just a "reasonable" number that was chosen to limit static memory usage. Could we increase the limit, or make the arg list dynamically resize?

**Comment by dbabokin** [comment]
@DeepakRajendrakumaran Let's make the number of arguments dynamic. Otherwise it will hit us again.

**Comment by dbabokin** [comment]
I've increased the number of arguments to 1024 as a temporary fix. New build should be ready shortly (will be available for [Linux](https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build%2Fispc-trunk-linux.tar.gz?job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DUbuntu1604%2C%20LLVM_VERSION%3Dlatest) and [Windows](https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build%2Fispc-trunk-windows.zip?job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202017%2C%20LLVM_VERSION%3Dlatest) shortly). Commit id of the build with the fix is ba55b18.

**Comment by dbabokin** [comment]
Fixed.
