### ISSUE TITLE
Missing #include <stdarg.h>

### ISSUE THREAD

**Issue by yurivict** [ispc/ispc#1643]
```
/usr/ports/devel/ispc/work/ispc-1.12.0-115-g41876e21/src/main.cpp:383:9: error: use of undeclared identifier 'va_start'
        va_start(args, format);
        ^
/usr/ports/devel/ispc/work/ispc-1.12.0-115-g41876e21/src/main.cpp:385:9: error: use of undeclared identifier 'va_end'
        va_end(args);
        ^
/usr/ports/devel/ispc/work/ispc-1.12.0-115-g41876e21/src/main.cpp:389:9: error: use of undeclared identifier 'va_start'
        va_start(args, format);
        ^
/usr/ports/devel/ispc/work/ispc-1.12.0-115-g41876e21/src/main.cpp:391:9: error: use of undeclared identifier 'va_end'
        va_end(args);
        ^
```

**Comment by dbabokin** [comment]
What compiler and standard library are you using? (and what version)

I'll add `#include <stdarg.h>`, but would be good to have a record where it's reproducible.

**Comment by yurivict** [comment]
It's FreeBSD 12 with clang-8.

```man va_start``` says that this header is necessary, so it should be added in every file where you use ```va_start```, regardless of the system.

**Comment by dbabokin** [comment]
I've added `<cstdarg>`, which is c++ version of `<stdarg.h>`. This will fix the problem.

Obviously, in the libraries that we test with, `<cstdarg>/<stdarg.h>` is included indirectly. We are testing with VS, libstdc++ (c++ library, which comes with gcc and typically used on Linux) and libc++ (c++ library, which comes with clang, used on macOS and optionally on Linux). So that's surprising that we have a problem on FreeBSD.

**Comment by yurivict** [comment]
There is no commit though.

**Comment by dbabokin** [comment]
It's in PR #1644, I'm waiting for CI to complete.

**Comment by dbabokin** [comment]
Merged.
