### ISSUE TITLE
How to specify x86_64 for Linux64 only?

### ISSUE THREAD

**Issue by jiapei100** [ispc/ispc#1751]
Sorry for my naive question. How to specify **x86_64** for **Linux64** only?

```console
ISPC_IA_TARGETS                 *sse2-i32x4,sse4-i32x4,avx1-i32x8,avx2-i32x8,avx512knl-i32x16,avx512skx-i32x16
```

Thank you

**Comment by cloudhan** [comment]
https://ispc.github.io/ispc.html#selecting-32-or-64-bit-addressing

**Comment by dbabokin** [comment]
@jiapei100 I'm not sure that I underdtand your question. Pease let me know if you have further questions after checking the documentation.

**Comment by jiapei100** [comment]
@cloudhan @dbabokin 

Hi, Thank you for your reply. Thanks... I was just about to compile **ispc** from scratch, and now I'm following [https://github.com/ispc/ispc/wiki/Building-ispc](https://github.com/ispc/ispc/wiki/Building-ispc). The **cmake** configuration set `ISPC_IA_TARGETS                 *sse2-i32x4,sse4-i32x4,avx1-i32x8,avx2-i32x8,avx512knl-i32x16,avx512skx-i32x16` by default.

It seems **LLVM** must be manually installed before **ispc**??

```console
CMakeFiles/ispc.dir/src/llvmutil.cpp.o: In function `lDumpValue(llvm::Value*, std::set<llvm::Value*, std::less<llvm::Value*>, std::allocator<llvm::Value*> >&)':
llvmutil.cpp:(.text._ZL10lDumpValuePN4llvm5ValueERSt3setIS1_St4lessIS1_ESaIS1_EE+0xb1): undefined reference to `llvm::Value::dump() const'
CMakeFiles/ispc.dir/src/opt.cpp.o: In function `Optimize(llvm::Module*, int)':
opt.cpp:(.text._Z8OptimizePN4llvm6ModuleEi+0x48): undefined reference to `llvm::Module::dump() const'
opt.cpp:(.text._Z8OptimizePN4llvm6ModuleEi+0x143a): undefined reference to `llvm::Module::dump() const'
CMakeFiles/ispc.dir/src/opt.cpp.o: In function `IntrinsicsOpt::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text._ZN13IntrinsicsOpt15runOnBasicBlockERN4llvm10BasicBlockE+0x118a): undefined reference to `llvm::Value::dump() const'
opt.cpp:(.text._ZN13IntrinsicsOpt15runOnBasicBlockERN4llvm10BasicBlockE+0x11f8): undefined reference to `llvm::Value::dump() const'
CMakeFiles/ispc.dir/src/opt.cpp.o: In function `InstructionSimplifyPass::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text._ZN23InstructionSimplifyPass15runOnBasicBlockERN4llvm10BasicBlockE+0x2e3): undefined reference to `llvm::Value::dump() const'
opt.cpp:(.text._ZN23InstructionSimplifyPass15runOnBasicBlockERN4llvm10BasicBlockE+0x34f): undefined reference to `llvm::Value::dump() const'
CMakeFiles/ispc.dir/src/opt.cpp.o: In function `ImproveMemoryOpsPass::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text._ZN20ImproveMemoryOpsPass15runOnBasicBlockERN4llvm10BasicBlockE+0x556a): undefined reference to `llvm::Value::dump() const'
CMakeFiles/ispc.dir/src/opt.cpp.o:opt.cpp:(.text._ZN20ImproveMemoryOpsPass15runOnBasicBlockERN4llvm10BasicBlockE+0x55d6): more undefined references to `llvm::Value::dump() const' follow
CMakeFiles/ispc.dir/src/opt.cpp.o: In function `DebugPass::runOnModule(llvm::Module&)':
opt.cpp:(.text._ZN9DebugPass11runOnModuleERN4llvm6ModuleE+0x26): undefined reference to `llvm::Module::dump() const'
CMakeFiles/ispc.dir/src/opt.cpp.o: In function `PeepholePass::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text._ZN12PeepholePass15runOnBasicBlockERN4llvm10BasicBlockE+0xa34): undefined reference to `llvm::Value::dump() const'
opt.cpp:(.text._ZN12PeepholePass15runOnBasicBlockERN4llvm10BasicBlockE+0xaa3): undefined reference to `llvm::Value::dump() const'
CMakeFiles/ispc.dir/src/opt.cpp.o: In function `ReplaceStdlibShiftPass::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text._ZN22ReplaceStdlibShiftPass15runOnBasicBlockERN4llvm10BasicBlockE+0x776): undefined reference to `llvm::Value::dump() const'
opt.cpp:(.text._ZN22ReplaceStdlibShiftPass15runOnBasicBlockERN4llvm10BasicBlockE+0x7e6): undefined reference to `llvm::Value::dump() const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/ispc.dir/build.make:1546: recipe for target 'bin/ispc' failed
make[2]: *** [bin/ispc] Error 1
make[2]: Leaving directory '....../ispc/ispc/build_18.04'
CMakeFiles/Makefile2:148: recipe for target 'CMakeFiles/ispc.dir/all' failed
make[1]: *** [CMakeFiles/ispc.dir/all] Error 2
make[1]: Leaving directory '....../ispc/ispc/build_18.04'
Makefile:152: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by dbabokin** [comment]
We recommend building LLVM. See scripts/build.sh or files in docker/* to see how we do that with alloy.py

**Comment by dbabokin** [comment]
Our how-to manuals for building from sources are a bit outdated, I'll need to update them. So the most current build recipes can be found in docker files (which bootstrap from scratch) or in CI files (TravisCI and Appveyor), but they don't do full bootstrapping, as building LLVM for every commit is too costly.

Why do we recommend to build LLVM manually? Because this is not yet-another-library-dependency for ISPC, but essential foundation that we build on top of. So it's critical to get it right. There are several aspects of getting it right:

- enable assertions and dumps. ISPC is exercising code paths in LLVM, which are not well tested by other front-ends, as we generate heavy vector code. So, if we encounter some bug in LLVM, it's better to fail on assert, rather than spend time investigating wrong generated for or seg fault. If you really want to build with LLVM, which doesn't have asserts/dumps enabled, you can pass ``-DISPC_NO_DUMPS=ON`` to cmake when building ISPC.
- apply all recommended patches. All the patches that we recommend are backports of the fixes in trunk. As I mentioned, we do find bugs in LLVM. Sometimes by the time when we find these bugs, LLVM versions that we are interested in are already released. So we backport these patches and store in our repo. If these patches are not applied, ISPC will have known failures. In case of 10.0 it affects only avx512skx-i8x64 and avx512skx-i16x32 targets.
- enable all required LLVM targets, which include x86, Arm and WebAssembly. Any of these targets may be disabled through ISPC cmake options (ARM_ENABLED, WASM_ENABLED are in CMake, X86_ENABLED is coming soon).

Please let me know if you have any further questions. I'll close the issue for now. Feel free to reopen.
