### ISSUE TITLE
Error: When using a "generic-*" compilation target, object file output can not be used.

### ISSUE THREAD

**Issue by jiapei100** [ispc/ispc#1760]
Alright, after my [1758 PR](https://github.com/ispc/ispc/pull/1758), I reached here. If I enable ** ISPC_INCLUDE_EXAMPLES            ON**, I'll receive the following **ERROR** message:

```
Error: When using a "generic-*" compilation target, object file output can not be used.
```

I may have to use ** ISPC_INCLUDE_EXAMPLES            OFF** in order to have ispc built...

BTW, my configuration is **generic-x64**.

Cheers

**Comment by dbabokin** [comment]
That's correct, with ``generic-*`` targets you can't use object file as output, you need to define C++ output and pass a header file, which define number of stdlib intrinsics.

What do you exactly mean by "my configuration is generic-x64"? Where do you set this target?

Also, do you really need generic targets or just want to explore what they do? The reasons I'm asking is because generic target are not expected to work well and I'm considering removing them. If we need this functionality for real, we need to re-implement them from scratch.
