### ISSUE TITLE
2 Questions about new 1.14 GPU support..

### ISSUE THREAD

**Issue by oscarbg** [ispc/ispc#1842]
Hi,
first congrats for new GPU support via level zero API..

have two questions:

1) even 1.14 prebuilt binaries aren't yet ready, 1.14 RN mention "GPU-enabled Linux binary" so seems ISPC prebuilt Windows binary will not have GPU support even L0 API and drivers are avaiable on Windows and being used by Intel OneAPI SDK  DPC++ Compiler if not being mistaked.. so question is: it's possible to build ISPC 1.14 for Windows with GPU enabled backend even Intel will not provide Win enabled builds currently? or will require further code changes..

2) also you mention Gen9 support only.. again similar question as before.. is ISPC 1.14 source code ready for later Gen GPUs like Gen11 (icelake) or even upcoming Tigerlake (gen12) and pending on possible Level zero driver support for these later GPUs or will require also source level changes?

Thanks..

**Comment by dbabokin** [comment]
Thanks for the feedback!

1. One dependency is missing on Windows - driver build, which contains all the changes that we need. Once it's available, we will add Windows. I think it will be added to Github Actions CI, so you won't need to wait for another release. But I'm not sure about timeline of the driver changes availability.
2. Gen9 was used as a focus for this "alpha" release, Gen11/Gen12 will be added later. Note that at this stage of development it makes sense to focus on single platform, rather than to cover as many as possible.

**Comment by oscarbg** [comment]
Thanks for fast response..

good to know Windows support is only waiting for a driver update and really I'm fine right now with Gen9 as this is the HW I have :-)

**Comment by oscarbg** [comment]
any update on a supporting Windows driver build? seems there is a current beta driver with support for OneApi beta 10 and level zero 1.0 so pretty recent and similar features as Intel Neo Linux..

**Comment by aneshlya** [comment]
Latest version of the Windows driver contains necessary features and we may include ISPC with GPU support for Windows in our next release. However, our current focus is Linux so at the moment we do not promise the same level of quality on Windows as on Linux.

**Comment by oscarbg** [comment]
Hi @aneshlya ,
can share any updates?
seems repo has gained some (full?) Windows support recently with commits like:
https://github.com/ispc/ispc/commit/5da62f46dfdfb55b961d54cfb92025e3f1ce37fa
so I ask some quick questions, as have some doubts upon quick inspection:
1)seems some tests have been already run on Win driver 100.9168:
https://github.com/ispc/ispc/commit/e9efd6148a2e2d019a24b026d057e397fa23a2bf
2) but also seems using ocloc64.dll file required for GPU Win support instead of igc64.dll, altough recent drivers this file is unexisting (seen from commit: https://github.com/ispc/ispc/commit/7157670a4bfdc8715cd40dc6744edcd2c5de80b7#diff-91eede7716565a700586788e3f9d285985bf5c449a366cdd3b28fc37c073a616 )

also trying to get a Windows GPU(Gen) enabled build from Github Actions site with no luck like:
https://github.com/ispc/ispc/suites/2074936961/artifacts/41984870
on
https://github.com/ispc/ispc/actions/runs/580465136

so seems anyone of Github actions Windows artifacts are GPU enabled builds, right?
are some of these Github CI builds, planned to be GPU enabled, so early testing on Win GPU builds can be done even before official release?
thanks..

**Comment by aneshlya** [comment]
Hi @oscarbg,
We've added initial Windows support to ISPC for Gen and working on its stabilizing.  Compilation through SPIR-V works fine on Windows. You're right that ocloc64.dll is not available in a public driver and we're not going to support L0 binary (ahead of time compilation) for Windows in the upcoming release (but it will be enabled in the future).
Is SPIR-V path sufficient for you or do you need L0 binary as well?

We don't have GPU-enabled pre-release builds publicly available. But thanks for asking! Since our GPU support becomes more mature, we'll consider making GPU-enabled builds available for early testing on Github.

**Comment by oscarbg** [comment]
Hi @aneshlya,
really don't have a need for AOT & L0 binary support.. SPIR-V is OK for me..
thanks for the info and for considering making available early GPU builds..

**Comment by oscarbg** [comment]
Hi,
just my every 2 to 3 months asking for an update.. basically if ISPC Win GPU support is stable enough so we can expect to be "previewed" on next ISPC release, hopefully soon..
thanks..

**Comment by dbabokin** [comment]
@oscarbg it's coming. 1-2 week, I keep my fingers crossed 🤞
