### ISSUE TITLE
Wrong or not intuitive type cast

### ISSUE THREAD

**Issue by mergian** [ispc/ispc#1886]
In the following code example I would expect that the varying function will be called. ```float``` by default is varying, so a cast to ```(float)``` should be ```(varying float)```. Instead ISPC casts it into ```(uniform float)```. The example code should print:
```
uniform func
varying func
[15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000]
```
but instead creates an infinite recursion.

Tested with ISPC 1.14.1 on Linux.

#### test.ispc
```c++
float func(float A, float B) {
        print("varying func\n");
        return A * B;
}

float func(float A, uniform float B) {
        print("uniform func\n");
        return func(A, (float)B); // adding 'varying' in the type cast fixes the problem.
}

export void test() {
        float A = 5;
        uniform float B = 3;
        print("%\n", func(A, B));
}
```

#### test.cpp
```c++
extern "C" void test(void);

int main(int argc, const char** argv) {
        test();
        return 0;
}
```

#### build steps
```bash
ispc -o test.o test.ispc
g++ test.o test.cpp
./a.out
```

**Comment by dbabokin** [comment]
Looks like a bug.

**Comment by DeepakRajendrakumaran** [comment]
The reason for this is how we interpret '(float)' and how we resolve unbounded.

Currently, how it works is when we see a type with variability not explicitly specified(like 'float'), we assigned 'unbounded' variability to it.
uniform float = uniform
varying float = varying
float = unbounded

for TypeCastExpr, we assign the variability of the fromType if unbounded. So, for '(float)B'
if B = uniform float -> the unbound variability is set to uniform
if B = varyingfloat -> the unbound variability is set to varying

This behaviour appears incorrect since it inherently defeats the purpose of typecasting if the base type is same.

Will need to experiment to see if setting unbounded directly to 'varying' breaks anything else.

**Comment by DeepakRajendrakumaran** [comment]
This needs some introspection. 

1. Our stdlib seem to be written under the assumption that current behaviour explained in my previous post is the expected behaviour. Changing it would mean modifying stdlib
2. If this change were to be made, types that used to be 'uniform' before would now be 'varying'. This has potential to break existing codebase. Assuming someone currently using ispc has code

float foo(uniform float A) {
        print("varying func\n");
        return A * B;
}

float goo(uniform float B) {
        print("uniform func\n");
        return foo((float)B); // currently this will be foo(uniform float)
}

If we were to change this, now the call would be 'foo(varying float)' and  compilation will fail at the 'foo' function call since we cannot typecast from 'varying' to 'uniform'

@aneshlya @dbabokin - thoughts?

**Comment by dbabokin** [comment]
This is really tricky bug. This is NOT an intended behavior. This is really potential trap even for experienced users (as we see it in stdlib).

I suggest requiring fully qualifying the type in type cast and fixing all known code, including stdlib. We'll need to do that in two stages - making this a warning and making this an error. We'll need to wait a release or two before converting this to an error.

**Comment by dbabokin** [comment]
Looking at PR #1978 I realized that the proposed fix is too aggressive. For most of the cases it's convenience feature, which has conservative default (i.e. don't change variability). If the variability needs to be changed, it will be changed by implicit convert. There's no possibility for mistake. So it's a good feature, which makes the language more compact and easier to write on.

The case with function call is different. In the context of function argument this type of conversion matters and may lead to different overload resolution. So it's potentially dangerous.

Ideal fix would be to warn users if the convert leads to different variability of the function argument and suggest to use explicit variability in this case. Documentation also needs to be clarified to explain this behavior explicitly.

I'm wondering if there are other contexts which need explicit variability resolution. It seems that calling a function is only such case.
