### ISSUE TITLE
LLVM monorepo

### ISSUE THREAD

**Issue by sjoerdmeijer** [ispc/ispc#1889]
Hi guys, just a wild idea, I don't know if it really belongs here as an issue, but didn't know a better place, so here we go.
I was wondering if you've considered proposing integrating ispc into the llvm monorepo? I see quite a few mutual benefits. It would be a really nice addition to the llvm projects, IMHO, would probably increase the exposure to ispc, and thus open up ispc for contributions from the llvm community. For ispc, hopefully a better integration would be less maintenanc? But I am only guessing, and guess rebasing on new llvm release can be quite a bit of work. ispc could also leverage some of the clang/llvm infrastructure. For example, I just had a first quick look at the architecture/cpu/target parsing in ispc, for which I think a more complete implementation exist in clang/llvm (not that it's really great, but it's there), so this is one example of some duplication.
I of course do see that this would require some effort, but IMO would make sense long term. Any thoughts? :)

**Comment by dbabokin** [comment]
Thanks for raising this question. It would be good to have the answer documented somewhere.

First of all, I don't think it's practically feasible, as ISPC has more build dependancies than LLVM. Considering ISPC for CPU we have m4, bison, and flex. When it comes to GPU, we require a bunch of back-end libraries coming from Intel GPU driver, SPIR-V translator, and vc-intrinsics lib.

Being bound to LLVM has notable downsides:
(1) this means lack of freedom for release cycles.
(2) this also creates a problem for GPU backend. Even through ISPC interfaces with GPU backend through SPIR-V, it does a number of optimizations before generating SPIR-V, which makes it desirable to control LLVM version for stability purposes.

The upsides are also clear:
(1) no breakages from LLVM trunk - not a big deal on practice. It requires several fixes for every new LLVM version, but these fixes typically not complex.
(2) this would stop people from building ISPC with "stock" LLVM, which is a typical way to get broken ISPC build in a package manager.

Things like sharing code is not a big deal. Those parts that we need to share, we typically share as a library functionality. Unfortunately, there are pieces that we'd like to share / borrow, but cannot due to project structure (like ABI lowering in clang). Integrating to monorepo would not help here. As for target parsing, ISPC targets are different from clang targets, so they need to be parsed differently.

I'll close the issue, as I don't see anything actionable here, but feel free to comment or reopen if needed.

**Comment by sjoerdmeijer** [comment]
The LLVM project is a compiler toolbox, and some tools in the LLVM project are part o af toolchain. And the LLVM project  does not provide full toolchains. For example, the AMDGPU and WASM backends are perhaps a bit different than other backends as they are part of rich runtime. Another example, C-libraries and math libraries are not present (although one is in development). In creating toolchains off the LLVM projects, runtimes and libraries are needed that are not part of the LLVM project. As such, I don't see how this could be a problem:

> (1) this means lack of freedom for release cycles.

As essentially this what people do: create CPU, GPU, embedded toolchains, etc. based on the LLVM projects.  

> his also creates a problem for GPU backend. Even through ISPC interfaces with GPU backend through SPIR-V, it does a number of optimizations before generating SPIR-V, which makes it desirable to control LLVM version for stability purposes.

I can't comment  technically on this, but I see this as yet another great illustration of potential benefits: SPIR-V is discussed regularly on the LLVM mailinglist as parts of the LLVM community are very interested in supporting SPIR-V in some form, for example having a SPIR-V backend and tools. Different parties in the LLVM community are also involved in Khronos working on the Khronos SPIR-V tools.

I don't think your technical points are showstoppers here. At least, I don't see them. Also, keep in mind that the LLVM project can support tools/projects in different ways. For example, recently so called incubator projects are supported. And also, when a project is included not everything needs to be right from the moment of inclusion. For example, the inclusion of a Fortran front-end was started, which needs to be migrated to be more in the spirit of LLVM.

Regarding an actionable point: you could consider writing a RFC (request for comment) to the LLVM mailing list proposing the idea, and what exactly inclusion could mean, just to test the water without committing to anything.

Again, I don't see technical obstacles, but it of course would be a big change for the ispc project which would require an investment and who am I to say something about the ispc project?! :-) But again, I think the benefits would be great for both ispc and llvm.

**Comment by sjoerdmeijer** [comment]
Ah, and forgot to thank you for your reply and elaborating on this!
(I appreciate it's a long shot, but hope you consider an RFC to the llvm list :-))

**Comment by dbabokin** [comment]
At this point I see downsides as blocking issues. Being tired to LLVM trunk is very restricting.
In the future we will reconsider if joining LLVM monorepo worth it. Specifically, once GPU backend matures, we will have more definite answers to dependencies question.
One thing that would be distraction for us and we can't afford it now - change of workflows (issues, PRs, release practices, etc).

**Comment by sjoerdmeijer** [comment]
Ok, fair enough, and thanks for replying!
