### ISSUE TITLE
Performance Warning: Gather required to load value.  (unexpected) 

### ISSUE THREAD

**Issue by ovilla** [ispc/ispc#1892]
I would really appreciate some help understanding what I am doing wrong.
At glance this code should not have any gather.

```
struct char4 {
    int8 x, y, z, w;
};

export void foo(uniform char4 input[], uniform int output[]) {
    foreach(i = 0 ... 16 )
    {       
        char4 j = input[i];
        if (j.x != 0) 
            output[i] = 0;
    }
}
```

```
<source>:8:19: Performance Warning: Gather required to load value. 

        char4 j = input[i];

                  ^^^^^^^^
```

See compilation here:  https://ispc.godbolt.org/z/MdKhYn
Thanks!

Oreste

**Comment by ovilla** [comment]
I also tried short vectors   ```int8<4>``` , assuming my ```char4``` struct was not understood by the complier, but still I did not obtain the desired vectorization.

I then realized from the manual that:

> Note: ispc does not use these short vectors to facilitate program vectorization; they are purely a syntactic convenience. Using them or writing the corresponding code without them shouldn't lead to any noticeable performance differences between the two approaches.

Seems that what I was expecting is not supported.

**Comment by DeepakRajendrakumaran** [comment]
Here is a very slightly simplified version with IR - https://ispc.godbolt.org/z/fGh3z1
The reason for gather is the code trying to access individual element of structs . In this case because of the foreach loop, we have vector access to the array of structs. The ispc solution here is to copy individual struct elements from 'input' to 'output'. Since, input[0].x, input[1].x etc are not contiguous memory locations, we resort to gather.

Coming to your specific example(I modified it slightly since gather for int8 causes some funky replacement + I removed the if condition) - https://ispc.godbolt.org/z/aT3zvW . In this case, it's similar but we recognize that only element x is used and only that gather is used.

I need to think if there is some way to avoid gather here. @dbabokin - thoughts?

**Comment by DeepakRajendrakumaran** [comment]
> I also tried short vectors `int8<4>` , assuming my `char4` struct was not understood by the complier, but still I did not obtain the desired vectorization.
> 
> I then realized from the manual that:
> 
> > Note: ispc does not use these short vectors to facilitate program vectorization; they are purely a syntactic convenience. Using them or writing the corresponding code without them shouldn't lead to any noticeable performance differences between the two approaches.
> 
> Seems that what I was expecting is not supported.

In your case a more relevant ispc feature might be 'soa' support.  https://ispc.github.io/ispc.html#structure-of-array-types

**Comment by ovilla** [comment]
> Here is a very slightly simplified version with IR - https://ispc.godbolt.org/z/fGh3z1
> The reason for gather is the code trying to access individual element of structs . In this case because of the foreach loop, we have vector access to the array of structs. The ispc solution here is to copy individual struct elements from 'input' to 'output'. Since, input[0].x, input[1].x etc are not contiguous memory locations, we resort to gather.
> 
> Coming to your specific example(I modified it slightly since gather for int8 causes some funky replacement + I removed the if condition) - https://ispc.godbolt.org/z/aT3zvW . In this case, it's similar but we recognize that only element x is used and only that gather is used.
> 
> I need to think if there is some way to avoid gather here. @dbabokin - thoughts?

but I think using 

```
struct char4 {
    float x, y, z, w;
};
```

we load128bit per element, instead of 32bit.

Indeed looking at the geneted ASM we can see 4 times:

```
        vmovaps zmm0, zmmword ptr [rip + .LCPI1_0] # zmm0 = [0,16,32,48,64,80,96,112,128,144,160,176,192,208,224,240]
        vxorps  xmm1, xmm1, xmm1
        kxnorw  k1, k0, k0
        vgatherdps      zmm1 {k1}, zmmword ptr [rdi + zmm0]
        vmovaps zmm2, zmmword ptr [rip + .LCPI1_1] # zmm2 = [4,20,36,52,68,84,100,116,132,148,164,180,196,212,228,244]
        vxorps  xmm3, xmm3, xmm3
        kxnorw  k1, k0, k0
        vgatherdps      zmm3 {k1}, zmmword ptr [rdi + zmm2]
        vmovaps zmm4, zmmword ptr [rip + .LCPI1_2] # zmm4 = [8,24,40,56,72,88,104,120,136,152,168,184,200,216,232,248]
        vxorps  xmm5, xmm5, xmm5
        kxnorw  k1, k0, k0
        vgatherdps      zmm5 {k1}, zmmword ptr [rdi + zmm4]
        vxorps  xmm6, xmm6, xmm6
        vmovaps zmm7, zmmword ptr [rip + .LCPI1_3] # zmm7 = [12,28,44,60,76,92,108,124,140,156,172,188,204,220,236,252]
        kxnorw  k1, k0, k0
        vgatherdps      zmm6 {k1}, zmmword ptr [rdi + zmm7]
```

or am I misunderstanding?

**Comment by DeepakRajendrakumaran** [comment]
I think you might be looking at the first case I was using as an explanation. This - https://ispc.godbolt.org/z/rqEK65 is for your use case with float

**Comment by ovilla** [comment]
Thanks. As soon as I change the ```foreach``` from 16 to something else I get back the "gather" warning. 
I used 16 only to demonstrate the problem, but that number is an input to the function itself (still a multiple of 16, but it could be 256 for instance).

(i.e. 256) https://ispc.godbolt.org/z/Yv77M4   

Also the input array is really made of x,y,z,w bytes and not floats. Of course I can change that outside, but I feel is not right as I would use 4x more memory and fetch 4x more data.

**Comment by pbrubaker** [comment]
Hey @ovilla,

The problem here is that ISPC is interpreting your input as Array of Structures, but you're attempting to use it as a Structure of Arrays.  The way you've told ISPC your memory is laid out for `input` is that it is char4 structs stored linearly.

So the pattern in memory is this:  `x0, y0, z0, w0, x1, y1, z1, w1, x2, y2, z2, w2...`
And what you're loading into is: `x0, x1, x2, x3; y0, y1, y2, y3; z0, z1, z2, z3, w0, w1, w2, w3`

There are a couple ways to deal with this.  If you can change the data layout, do because that'll be faster.  For the moment the storage class doesn't matter, we can change that later, but here's an example of how I would do this as floats.  We can change the storage class later.

Essentially what you need to do is change the layout in memory, or transpose what is in memory into what ISPC expects.  Here are a couple examples.

https://ispc.godbolt.org/z/WecvT5

The first is `foo2()` that shows how to use ISPC's built in functions to transpose the loads and stores.  Make sure to read the [docs here](https://ispc.github.io/ispc.html#data-conversions), they do a decent job of explaining this.  This only works with floats in the standard library (other functions coming soon! but there may be some code I can share in the meantime.)  There is another way around this if you can re-arrange your data.  If you can store things like this in memory then a gather, or a transpose won't be necessary.

`x0, x1, x2, x3; y0, y1, y2, y3; z0, z1, z2, z3, w0, w1, w2, w3`

Then you can do something like I showed in `foo3` but you have to account for differences in target width/programCount in your program.

Hopefully this helps!

**Comment by DeepakRajendrakumaran** [comment]
@pbrubaker  Thanks for the succinct explanation. 

@ovilla Neither the float type or the foreach limit(16 vs 256) is important. You can use an int8 instead and it's the same end result. I just used a 'float' in my code example to highlight the gather and why a gather is being used in this case(i.e the memory access).  I should have been clearer there in hindsight. Pete's explanation is clearer and hopefully makes sense. Feel free to let us know if you are still having issues.

**Comment by ovilla** [comment]
Thanks a lot for the support. 

I also feel I need to explain a little bit more in detail what is my overall goal and why I am a bit hesitant to modify data-types, etc.

There is this great micro-benchmarks collection https://github.com/zjin-lcf/oneAPI-DirectProgramming (I am not the author nor associated with the project) with more than 80 micro-benchs (and growing), for which there are CUDA, syscl, OpenMP implementations.

My idea was to start from an OpenMP or CUDA implementation of a simple micro-bench and **to modify as little as possible** to get an equivalent ispc implementation (and potentially to create a pull request for ispc if results are satisfactory).

I have settled to start with this simple kernel https://github.com/zjin-lcf/oneAPI-DirectProgramming/blob/master/all-pairs-distance-omp/main.cpp#L98.

I hope this gives a little bit more context on the type of changes that can/can't be done.

**Comment by DeepakRajendrakumaran** [comment]
Hi,

Sorry for the delayed response. Assuming you are targeting CPU with OpenMP as well, can you please attach the assembly created for https://github.com/zjin-lcf/oneAPI-DirectProgramming/blob/master/all-pairs-distance-omp/main.cpp#L98 . I'd like to compare .

**Comment by pbrubaker** [comment]
Closing this issue because it's inactive.  If you need further support please reopen the issue.
