### ISSUE TITLE
Uniform global function pointers always trigger size/layout mismatch warning when compiling for multiple targets

### ISSUE THREAD

**Issue by soulsource** [ispc/ispc#1942]
Hi!

I'm not 100% certain this is an issue in ispc, or if the warning is justified and I am just not seeing where I am making a mistake.

I've encountered the issue that no matter how I try to define a global function pointer, the compiler always emits the following warning:
```
test.ispc:3:12: Warning: Mismatch in size/layout of global 
        variable "blah" with different targets. Globals must not include 
        "varying" types or arrays with size based on programCount when 
        compiling to targets with differing vector widths. 
uniform BL blah;
           ^^^^
```

The variable is declared as
```
typedef void (* uniform BL)();
uniform BL blah;
```
I am relatively certain that the variable is a uniform function pointer not taking any parameters and not having any return value, so I don't really see how it depends on target memory layout...

**Comment by pbrubaker** [comment]
Here's a repro - thought it was just missing a uniform, but it seems more complicated than that.  It seems the compiler thinks this is a uniform pointer to varying?

https://ispc.godbolt.org/z/MGdbPG

**Comment by DeepakRajendrakumaran** [comment]
It's an ISPC specific thing. ISPC adds an extra function parameter representing mask which has target width.

See IR for above example with single target: https://ispc.godbolt.org/z/PfTjaa

Line 39 has the function call and the mask parameter is visible. Now, when compiling for sse and avx2, the default see width is 4 and avx width is 8. This means this call is different based on the target:

call void %blah_load(<4 x i32>..) for sse4
call void %blah_load(<8 x i32>..) for avx2

Similarly, the warning goes away if we compile for 2 targets having equivalent width since the function signature is same - https://ispc.godbolt.org/z/Tjv7bf

The question here is, since 'mask' is an internal ISPC representation should we not be giving this warning in this case.

**Comment by DeepakRajendrakumaran** [comment]
Note - This is only a problem because it's global.

For eg. this - https://ispc.godbolt.org/z/K3K1sq is fine currently

**Comment by dbabokin** [comment]
Declaring function as `unmasked` also solves the problem:
```c
typedef unmasked void (* uniform BL)();
uniform BL blah;
```

**Comment by dbabokin** [comment]
`extern` also has the same effect:
```c
typedef void (* uniform BL)();
extern uniform BL blah;
```

**Comment by dbabokin** [comment]
I'm closing the issue, please feel free to reopen or ask questions in this thread.
