### ISSUE TITLE
reduce_add() function return a wrong result

### ISSUE THREAD

**Issue by shiyingjin** [ispc/ispc#2085]
I have just write a simple example which computes the sum of all the values in an array.
The ispc code like below:
```c
uniform float sum(const uniform float array[], uniform int count) {
    float sum = 0;
    foreach (i = 0 ... count)
        sum += array[i];
    return reduce_add(sum);
}
```

And I wrote the test code to verify the result:
```c
TEST(ISPC, test_float_sum) {
  const int count = 1024;
  float array[count];

  for (int i = 0; i < count; i++) {
    array[i] = ((float)rand() / (float)(RAND_MAX)) * 10.0f;
  }

  float valid = 0.0f;
  for (int i = 0; i < count; i++) {
    valid += array[i];
  }

  float sum = sum_float(array, count);

  ASSERT_FLOAT_EQ(valid, sum);
}
```

Finally, `ASSERT_FLOAT_EQ` failed. The error message is:

Expected equality of these values:
  valid
    Which is: 5131.9121
  sum
    Which is: 5131.915

**Comment by dbabokin** [comment]
This is due to different order of arithmetic operations, which lead to the final result.

Neither of the results is absolutely correct, they are just different and both are within some epsilon from the real (mathematically correct) result. This is the nature of floating point arithmetics.

You can try doing partial sums + final reduction in C version and check the result. The most likely it will be the same is ISPC returns to you.

This basically means that if your algorithms are *that* sensitive to floating point precision, you either cannot vectorize them in this way, or need to control the order of operations where it matters.

I'm closing the issue, as I see nothing to fix here. Feel free to reopen or just comment.
