### ISSUE TITLE
Unexpected llvm.bswap.v8i32 intrinsic with LLVM 13

### ISSUE THREAD

**Issue by foutrelis** [ispc/ispc#2189]
Seems LLVM 13 needs a patch similar to the one applied to LLVM 12. [1]

I get the following error when building against my system's copy of LLVM 13, but I'm assuming the CI would fail in the same way if `XE_ENABLED=ON` was used.

```
InvalidFunctionCall: Unexpected llvm intrinsic:
 llvm.bswap.v8i32
make[5]: *** [aobench/CMakeFiles/xe_aobench_spv.dir/build.make:73: aobench/xe_aobench.spv] Error 6
```

Applying [disable-bswap-for-spir.txt](https://github.com/ispc/ispc/files/7423519/disable-bswap-for-spir.txt) to my system LLVM 13 allows me to rebuild ISPC 1.16.1 (w/ LLVM 13 fixes) on Arch Linux.

[1] https://github.com/ispc/ispc/blob/main/llvm_patches/12_0_disable-A-B-A-B-and-BSWAP-in-InstCombine.patch

**Comment by aneshlya** [comment]
This particular issue was fixed in v1.17.0 (still based on LLVM 12.0).
ISPC Xe-enabled build with LLVM 13 works fine but there are some issues with debug info still. 
We plan to have the next release based on LLVM 13. Meanwhile, I'm closing this issue. The rest of the work related to LLVM 13 for Xe will be tracked here: https://github.com/ispc/ispc/issues/2255
