### ISSUE TITLE
Undefined behaviour with -ON (N > 0)

### ISSUE THREAD

**Issue by qcoh** [ispc/ispc#2289]
#### Steps to reproduce 
Compile the following code (swap.ispc):

```
export void swap(uniform int N, uniform int X[], uniform int Y[]) {
	for (varying int i = 0; i < N; i++) {
		varying const int index_x = i;
		varying const int index_y = i;

		varying const float x_i = X[index_x];
		X[index_x] = Y[index_y];
		Y[index_y] = x_i;
	}
}
```

with

```
ispc swap.ispc --target=avx2 -O3
```
and 
```
ispc swap.ispc --target=avx2 -O0
```

#### Current behaviour
The first compilation produces the warnings:

```
swap.ispc:7:3: Warning: Undefined behavior: all program instances are writing to the same location! 
  X[index_x] = Y[index_y];
  ^^^^^^^^^^

swap.ispc:8:3: Warning: Undefined behavior: all program instances are writing to the same location! 
  Y[index_y] = x_i;
  ^^^^^^^^^^

swap.ispc:7:3: Performance Warning: Scatter required to store value. 
  X[index_x] = Y[index_y];
  ^^^^^^^^^^

swap.ispc:8:3: Performance Warning: Scatter required to store value. 
  Y[index_y] = x_i;
  ^^^^^^^^^^
```

while the second succeeds.

#### Expected behaviour
Not sure but the discrepancy between both is suspicious.

#### Other comment
I might misunderstand the UB warning and/or my own code but `X[index_x]` with a varying `index_x` is not the same location, right?

Attached are the object dumps if it helps (`ispc swap.ispc --target=avx2 -O0/-O3 -g -o swap.o && objdump -S -Mintel swap.o`):
[dump_O0.txt](https://github.com/ispc/ispc/files/8355099/dump_O0.txt)
[dump_O3.txt](https://github.com/ispc/ispc/files/8355101/dump_O3.txt)

#### Environment
Ubuntu 20.04 with ispc 1.17.0:

```
$ ispc --version
Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.17.0 (build commit 7ad8429369a4d5ce @ 20220128, LLVM 12.0.1)
```

**Comment by dbabokin** [comment]
That is expected behavior, which requires clarification. Please let me know if you think that it needs any specific clarification in the documentation.

The semantic of `X[index_x] = Y[index_y];` (assuming varying indexes) is to do N reads and N writes in parallel (N = TARGET_WIDTH). If any of values in `index_x` vector are the same, then the behavior is undefined. This is not a problem in is this specific example (i.e. I don't think that it will lead to incorrect code on any of existing targets), as all the values are the same, but it is the problem from programming model prospective. This would become a problem, if assigned values become not the same, what would be the expected behavior? Consider this:
```c
uniform int X[];
varying int index = 0;
X[index] = programIndex;
```
This would mean that this conflicting write to X[0]: `X[{0,0,0,0}] = {0,1,2,3}`. What should be the resulting value in X[0]? That is undefined as this is concurrent write. So this is what this warning warns about - compiler was able to detect that all of the values in `index_x` and `index_y` are the same, and hence the problem with undefined behavior. Note, it's easy to trick compiler to not detect that the values are the same (so the warning is not reported), but the undefined behavior will remain in runtime.

The second "issue" here, that `-O0` and `-O3` behave differently. It is because the warning depends on compiler analysis, which was not done at -O0. Compiler makes best effort to detect the problem, but it's not always capable to do so.

**Comment by pbrubaker** [comment]
Also just to add,(and I'm sure I've realized this by now) these are the lines at issue here.

```
for (varying int i = 0; i < N; i++) {
	varying const int index_x = i;
	varying const int index_y = i;
```

Since you initialize `i` to `0`, all lanes in the register contain 0.  As you increment `i` you will get `[1,1,1,1]`, `[2,2,2,2]` etc.

```
for (uniform int i = 0; i < N; i+=programCount) {
	varying const int index_x = i+programIndex;
	varying const int index_y = i+programIndex;
```

That code should give you more of what you were after I think.
