### ISSUE TITLE
ISPC with gcc on MinGW64 Linker Warning: corrupt .drectve at end of def file

### ISSUE THREAD

**Issue by zx-82** [ispc/ispc#2354]
I used to build ISPC on MinGW64 (without ispc-runtime lib) which worked fine.
Now after upgrading from ispc version 13 to 18  I get the following error when linking against ispc object files: 

Warning: corrupt .drectve at end of def file

**Comment by dbabokin** [comment]
[Stack overflow](https://stackoverflow.com/questions/25161814/warning-corrupt-drectve-at-end-of-def-file) suggests that it's caused by linking against "incompatible MSVC libs". So looks like it's the changes in your environment, which caused this problem. If you think still think it's ISPC problem, please reopen the issue.
