### ISSUE TITLE
Add VNNI functions

### ISSUE THREAD

**Issue by atafra** [ispc/ispc#2736]
ISPC can be used to implement very efficient convolution / machine learning kernels but unfortunately it's not possible to use AI acceleration instruction sets like VNNI. Unlike AMX, adding support for VNNI should be very easy because it operates on existing varying/vector types. Only a set of new functions are needed, which would directly map to VNNI instructions. Using LLVM intrinsics might also work but it would great to have native support, which would be preferable in production code.

For example, the following function would map to the `VPDPBUSD` instruction:

`varying int32 dpbusd(varying int32 src, varying uint8 a, varying int8 b);`

This would be equivalent with the following C intrinsic: https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#avx512techs=AVX512_VNNI&ig_expand=2692

The most important data type would be INT8, but it seems adding support for most VNNI instructions should be straightforward. The only exception might be BF16, which may require adding a BF16 data type to ISPC first, but it would be fine to add support for VNNI-BF16 later.

**Comment by aneshlya** [comment]
LLVM intrinsics corresponding to VNNI instructions operate not on specific int8/int16 types, but on packed `int32` types. ISPC should adhere to this. It will allow the packing of types that do not have native type support, such as `int4` or `bf16`, while still using the VNNI instruction.

Since the arguments for VNNI functions are most often loaded from memory and not from other operations, this should be acceptable. In the future, if we support a mix of different widths within one module, we may introduce cross-lane bitcasts to assist with packing inside the dot_acc functions.

The same applies to dp4a and neon intrinsics; they should be packed to i32.

Therefore, ISPC functions would look like this (the table is not finalized). On targets without native dot product support, the operation will be emulated.

| ISPC function | AVX  | AVX512  | Gen12+ | ARM |
|---|---|---|---|---|
| `varying int dot_acc_byte_us(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpbusd | vpdpbusd | No intrinsic support? [https://github.com/intel/vc-intrinsics/blob/master/GenXIntrinsics/include/llvm/GenXIntrinsics/Intrinsic_definitions.py#L1660](https://github.com/intel/vc-intrinsics/blob/master/GenXIntrinsics/include/llvm/GenXIntrinsics/Intrinsic_definitions.py#L1660) | |
| `varying int dot_acc_byte_us_sat(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpbusds | vpdpbusds | No intrinsic support? [https://github.com/intel/vc-intrinsics/blob/master/GenXIntrinsics/include/llvm/GenXIntrinsics/Intrinsic_definitions.py#L1660](https://github.com/intel/vc-intrinsics/blob/master/GenXIntrinsics/include/llvm/GenXIntrinsics/Intrinsic_definitions.py#L1660) | |
| `varying int dot_acc_byte_ss(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpbssd | 2 x vpdpbssd | Dp4a | VMLAL  |
| `varying int dot_acc_byte_ss_sat(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpbssds | 2 x vpdpbssds | Dp4a | |
| `varying int dot_acc_byte_uu(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpbuud | 2 x vpdpbuud | Dp4a | |
| `varying int dot_acc_byte_uu_sat(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpbuuds | 2 x vpdpbuuds | Dp4a | |
| `varying int dot_acc_word_us(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpwusd | 2 x vpdpwusd | Emulation | |
| `varying int dot_acc_word_us_sat(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpwusds | 2 x vpdpwusds | Emulation | |
| `varying int dot_acc_word_ss(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpwssd | vpdpwssd | Emulation | VMLAL  |
| `varying int dot_acc_word_ss_sat(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpwssds | vpdpwssds | Emulation | |
| `varying int dot_acc_word_uu(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpwuud | 2 x vpdpwuud | Emulation | |
| `varying int dot_acc_word_uu_sat(varying int src, varying unsigned int a, varying unsigned int b)` | vpdpwuuds | 2 x vpdpwuuds | Emulation | |

**Comment by aneshlya** [comment]
After careful consideration of various design approaches of exposing VNNI functions in ISPC stdlib I'm inclined towards the following set of functions in stdlib:

```
enum ISPC_PACKED_FACTOR {
    ISPC_PACKED_FACTOR_BYTE, // int8/uint8
    ISPC_PACKED_FACTOR_WORD, // int16/uint16
};
varying int32 dot_acc(varying int32 src, varying int32 a, varying int32 b, uniform ISPC_PACKED_FACTOR f)
varying int32 dot_acc(varying int32 src, varying uint32 a, varying uint32 b, uniform ISPC_PACKED_FACTOR f)
varying int32 dot_acc(varying int32 src, varying int32 a, varying uint32 b, uniform ISPC_PACKED_FACTOR f)
varying int32 dot_acc(varying int32 src, varying uint32 a, varying int32 b, uniform ISPC_PACKED_FACTOR f)
varying int32 dot_acc_sat(varying int32 src, varying int32 a, varying int32 b, uniform ISPC_PACKED_FACTOR f)
varying int32 dot_acc_sat(varying int32 src, varying uint32 a, varying uint32 b, uniform ISPC_PACKED_FACTOR f)
varying int32 dot_acc_sat(varying int32 src, varying int32 a, varying uint32 b, uniform ISPC_PACKED_FACTOR f)
varying int32 dot_acc_sat(varying int32 src, varying uint32 a, varying int32 b, uniform ISPC_PACKED_FACTOR f)

```
In these functions, `a` and `b` represent vectors of packed `int8` or `int16` types. Unsigned types should be packed into `uint32`, while signed types should be packed into `int32`. This design allows us to support even smaller types such as `int4` or even `int2` without needing to add native support for these types to the language.

This design also seamlessly extends to floating-point types. For example, if we need to access intrinsics for bfloat16, the function signature would be as follows:
```
enum ISPC_PACKED_FACTOR {
    ISPC_PACKED_FACTOR_BYTE, // int8/uint8
    ISPC_PACKED_FACTOR_WORD, // int16/uint16
    ISPC_PACKED_FACTOR_BF16, // bf16
};
float dot_acc_sat(varying int32 src, varying uint32 a, varying int32 b, uniform ISPC_PACKED_FACTOR f)
```

**Comment by atafra** [comment]
I don't really like the `ISPC_PACKED_FACTOR_BYTE` uniform parameter. I find it too verbose, and gives the impression that this value could be a variable, while in practice it should be defined at compile time (otherwise, it cannot be translated to a single instruction so it would defeat the purpose of these function). I would prefer either to express the type as part of the function name or as a template parameter (enum).

**Comment by atafra** [comment]
So based on HLSL, here's what I propose instead:

```
varying uint32 dot4add_u8packed(varying uint32 a, varying uint32 b, varying uint32 acc);
varying int32  dot4add_i8packed(varying uint32 a, varying uint32 b, varying int32 acc);
varying int32  dot4add_i8packed_sat(varying uint32 a, varying uint32 b, varying int32 acc);
...

varying uint32 dot2add_u16packed(varying uint32 a, varying uint32 b, varying uint32 acc);
varying float   dot2add_bf16packed(varying uint32 a, varying uint32 b, varying float acc);
...
```

**Comment by aneshlya** [comment]
`ISPC_PACKED_FACTOR_BYTE` uniform parameter would be optimized so it will not produce any additional control flow instructions.
However I really like `dot2add` and `dot4add` naming which has this "factor" information compactly inside!

The rationale for distinguishing between signed and unsigned packed types using 32-bit parameters is to reduce the number of distinct stdlib functions and instead overload them using function parameters. The VNNi set includes instructions for all combinations of signed/unsigned packed types so it will be more functions then in HLSL. 
1. 
When we have information about the sign in function parameters type we can do:
```
varying uint32 dot4add_packed(varying uint32 a, varying uint32 b, varying uint32 acc);
varying int32 dot4add_packed(varying uint32 a, varying int32 b, varying int32 acc);
varying int32 dot4add_packed(varying int32 a, varying int32 b, varying int32 acc);
varying uint32 dot4add_packed_sat(varying uint32 a, varying uint32 b, varying uint32 acc);
varying int32 dot4add_packed_sat(varying uint32 a, varying int32 b, varying int32 acc);
varying int32 dot4add_packed_sat(varying int32 a, varying int32 b, varying int32 acc);
varying uint32 dot2add_packed(varying uint32 a, varying uint32 b, varying uint32 acc);
. . . 
varying float  dot2add_bf16packed(varying uint32 a, varying uint32 b, varying float acc);
```
2.
If we were to encode all this information in the function name, it would look like this:
```
varying uint32 dot4add_u8u8packed(varying uint32 a, varying uint32 b, varying uint32 acc);
varying int32 dot4add_u8i8packed(varying uint32 a, varying uint32 b, varying int32 acc);
varying int32 dot4add_i8i8packed(varying uint32 a, varying uint32 b, varying int32 acc);
varying uint32 dot4add_u8u8packed_sat(varying uint32 a, varying uint32 b, varying uint32 acc);
varying int32 dot4add_u8i8packed_sat(varying uint32 a, varying uint32 b, varying int32 acc);
varying int32 dot4add_i8i8packed_sat(varying uint32 a, varying uint32 b, varying int32 acc);
varying uint32 dot2add_u16u16packed(varying uint32 a, varying uint32 b, varying uint32 acc);
. . . 
varying float  dot2add_bf16packed(varying uint32 a, varying uint32 b, varying float acc);
```
Intel GPUs and ARM (I think) are more similar to HLSL - they don't have different signed/unsigned combinations. Packed types, accumulator and result are either all signed or all unsigned.

If you think that there is no need to expose VNNI instructions for mixed signed/unsigned packed types, we can go with HLSL approach and have `varying uint32 dot4add_u8packed(varying uint32 a, varying uint32 b, varying uint32 acc);` etc.
If mixed signed/unsigned packed types might be needed, we can go either 1 or 2.

**Comment by atafra** [comment]
I think the problem with overloads is that they make the code harder to understand (it's easy to miss the difference between the packed uint32/int32 arguments), and ultimately the number of functions still remains the same (an overload is still a separate function definition). Also, `dot4add_packed` doesn't communicate that it operates on ints or how large are those ints, unlike `dot2add_bf16packed`. I find `dot4add_u8u8packed` also too verbose and harder to read. I don't think we need to deviate from HLSL here. But I like `dot4add_u8i8packed` for the mixed cases. How about the following instead?

```
varying uint32 dot4add_u8packed(varying uint32 a, varying uint32 b, varying uint32 acc);
varying int32  dot4add_i8packed(varying uint32 a, varying uint32 b, varying int32 acc);
varying int32  dot4add_u8i8packed(varying uint32 a, varying uint32 b, varying int32 acc);
varying uint32 dot4add_u8packed_sat(varying uint32 a, varying uint32 b, varying uint32 acc);
. . . 
varying float  dot2add_bf16packed(varying uint32 a, varying uint32 b, varying float acc);
```

So we would keep HLSL naming where possible (e.g. `dot4add_u8packed`), and add new functions only for the mixed integer operations (e.g. `dot4add_u8i8packed`). This means that for each integer type, ISPC would have 3 functions vs. 2 functions in HLSL. I think this would be an acceptable increase in number of functions and would keep the existing convention as much as possible.

**Comment by aneshlya** [comment]
This would work!
The ISPC stdlib frequently uses function overloading, and we don't typically encode type information in the naming. However, I agree that with packed types, having type information in the function name is the most clear and unambiguous approach.

Thanks for your input! It's great to have a user's perspective before implementation is done.
