### ISSUE TITLE
rsqrt discrepancy between avx2 and avx512

### ISSUE THREAD

**Issue by nurmukhametov** [ispc/ispc#2882]
`rsqrt` standard library function returns values that are not same for different `x86` ISAs.

For example, we have the following results for `avx2-i32x8` and `avx512skx-x16`.

```bash
avx2-i32x8: rsqrt(1309.0) = 0.027639
avx512skx-x16: rsqrt(1309.0) = 0.027640
```

It is the part of #2782.

**Comment by dbabokin** [comment]
I believe that it's not a valid complaint.

Let me bring a broader context here first. FP precision in modern compilers is governed by fp-model flags and the math library being used.

In GCC world it's very messy design when there's a default, which kinda strict (kinda - because it still doesn't guarantee bit reproducibility between platforms) and there are relaxation switches, most importantly `--fast-math`, which assume the whole bunch of specific things that can be done (and which can be managed through separate options). Plus different math libraries with different precision and performance guarantees can be used.

Another approach is implemented by MSVC and was adopted by Intel Compiler and now it's being pushed to Clang. It assumes that there's `--fp-model=[strict|precise|fast|fast2]` flag, which defines what can and cannot be done in terms of different FP transformation affecting precision. Plus FP library with different tradeoffs between performance and precision. Note that Intel Compiler default is `--fp-model=fast`, which is pretty relaxed mode optimized for the performance. ISPC design was following this philosophy - fast by default.

Note that performance difference between fast and accurate implementation of the libraries is **dramatic**. It easily could be 10x or more, depending on how accurate you want to be.

So, ideally ISPC needs to have `--fp-model=[strict|precise|fast|fast2]` flag and several modes of built-in library corresponding to that. We clearly have demand for both - bit accurate (at least within a single architecture, i.e. x86) and fast (but still with predictable level of accuracy - note, not very accurate, but predictable, measured in ULPs).

All that being said, I think just aligning AVX2 and AVX512 implementation is not a right thing to do. **_The right thing to do is to have two (or more) different levels for fp precision._** Not using `rsqrt14` on AVX512 make code slower, so it "breaks" some customers who are concerned about the performance.

One more thing that we should pay attention for is consistency between uniform and varying versions of FP calculations - they should be the same on any platform.

**Comment by nurmukhametov** [comment]
> ISPC design was following this philosophy - fast by default.

I don't think this has happened in the case of `rsqrt` function, at least because there is `rsqrt_fast` that looks like fast by default.

> So, ideally ISPC needs to have `--fp-model=[strict|precise|fast|fast2]` flag and several modes of built-in library corresponding to that. 

Ideally, yes. But we can assume here that the current implementation represents one of these models. Can we? Which one, by the way? Then for the assumed model, we still have questions such as, 'Is it OK to have different results between, for example, AVX2 and AVX512? And between AVX512*-x16 and AVX512*-x32?

> Not using `rsqrt14` on AVX512 make code slower.

Why so? Especially considering that not every AVX512 target is wide enough to fill 512-bit registers with data

**Comment by dbabokin** [comment]
>> ISPC design was following this philosophy - fast by default.

> I don't think this has happened in the case of `rsqrt` function, at least because there is `rsqrt_fast` that looks like fast by default.

`rsqrt_fast` provides direct access to hardware instruction, which is the fastest and the least accurate version of different implementations. `rsqrt` provides reasonably fast and reasonably accurate result. Note that hardware instructions designed with an assumption that the result can be refined with Newton-Raphson if needed. And that's exactly what happens in `rsqrt` implementation. Raw hardware `rsqrt` instruction is not accurate enough for most of the use cases for library calls of `rsqrt`.

> > So, ideally ISPC needs to have `--fp-model=[strict|precise|fast|fast2]` flag and several modes of built-in library corresponding to that.
> 
> Ideally, yes. But we can assume here that the current implementation represents one of these models. Can we? Which one, by the way? Then for the assumed model, we still have questions such as, 'Is it OK to have different results between, for example, AVX2 and AVX512? And between AVX512*-x16 and AVX512*-x32?

I think our default is more like `precise`, but I'm sure that there are cases when we diverge from it. `fast` is enabled by `--opt=fast-math`, at least the original idea was that. Recent LLVM versions got a lot of changes that are related to definition fp-models, it would be good to check if we use it properly for `--opt=fast-math`. But we don't have these modes for the library. 

> > Not using `rsqrt14` on AVX512 make code slower.
> 
> Why so? Especially considering that not every AVX512 target is wide enough to fill 512-bit registers with data

You are right, `rsqrt` and `rsqrt14` run equally fast, so I'm wrong about the speed if there's enough execution bandwidth (i.e. x4 and x8 targets). But `rsqrt14` instructions are more precise (error is less than 2^-14) than `rsqrt` (error is less than 1.5*2^-12).
