### ISSUE TITLE
Utilization of `SDOT`/`UDOT` for `dot4add_u8i8*` on ARM

### ISSUE THREAD

**Issue by Wunkolo** [ispc/ispc#2951]
This is a follow-up on #2736 to capture interest on an ARM implementation.

On ARM there is the [UDOT instruction](https://developer.arm.com/documentation/100069/0609/A64-SIMD-Vector-Instructions/UDOT--vector-) and [SDOT instruction](https://developer.arm.com/documentation/100069/0609/A64-SIMD-Vector-Instructions/SDOT--vector-) that would be a great candidate to implement the newly added `dot4add_u8i8*` functions.

**Comment by aneshlya** [comment]
Yes, we need to add target-specific implementations for ARM (and Xe). We've implemented `dot*` functions to evaluate how users will interact with them, assess their convenience, and determine any additional features needed in ISPC to facilitate easier dot products.

Could you share your experience if you've already used the `dot*` functions?

**Comment by Wunkolo** [comment]
> Could you share your experience if you've already used the dot* functions?

I haven't utilized it just yet, but I currently have an intent to use these 8-bit dot-product functions to accelerate [image convolution](https://en.wikipedia.org/wiki/Kernel_(image_processing)#Convolution) and [other image operations](https://github.com/Wunkolo/qAverageColor?tab=readme-ov-file#avx512-vnni).

**Comment by Wunkolo** [comment]
I have a proof-of-concept UDOT utilization here now, showing my particular use-case.
https://github.com/Wunkolo/qAverageColor/commit/afefda7592a2025c39b30b62851bb2847380f8ac

**Comment by aneshlya** [comment]
I looked closely to `UDOT`/`SDOT` instructions and they use mixed width vectors.
For example:
```
 <4 x i32> @llvm.aarch64.neon.sdot.v4i32.v16i8(<4 x i32> %a, <16 x i8> %b, <16 x i8> %c)
```
**Return Type**: <4 x i32>
The result is a 4-element vector of 32-bit integers.
**Operands**:
%a: <4 x i32>
This is the initial vector accumulator, where the dot product results will be accumulated.
%b: <16 x i8>
The first operand vector for the dot product. It consists of 16 signed 8-bit integers.
%c: <16 x i8>
The second operand vector for the dot product. It also consists of 16 signed 8-bit integers.

It doesn't directly map to ISPC because ISPC currently does not support mixed-width operands.

ISPC's existing dot* functions operate on packed data with the same vector width for all operands, which maps cleanly to x86 VNNI instructions.

While I could use NEON-specific instructions, this would require packing the data beforehand (and internally unpacking it during computation). Although this approach has unneeded packing/unpacking, it could still be faster than a generic implementation (need to check).
