### ISSUE TITLE
More efficient 3-component vector codegen

### ISSUE THREAD

**Issue by rkaric** [ispc/ispc#2955]
Given the following code: https://godbolt.org/z/bYnMnbPbo, ISPC can perform the 3-component operation more efficiently by using xmm registers and clearing the last lane after the bitwise AND. For example, This could be done with a static blend and a zero vector.

**Comment by nurmukhametov** [comment]
So, the issue is about this code using 3-component vector.

```ispc
struct FVector3
{
	float V[3];
};

uniform FVector3 VectorBitwiseAnd(const uniform FVector3 &Vec1, const uniform FVector3 &Vec2)
{
	uniform FVector3 Result;

	foreach(i = 0 ... 3)
	{
		Result.V[i] = floatbits(intbits(Vec1.V[i]) & intbits(Vec2.V[i]));
	}

	return Result;
}
```

To fix this, we need to support 3-wide vectors in `ReplaceMakedMemOps` (#2836).

But I don't expect the generated code to be exactly the same as the referenced intrinsic code. Note, intrinsic one uses `__m128` when ISPC code uses `float V[3];`.
